### ISSUE TITLE
Traceur modules are outdated; maybe note this, or don't use them?

### ISSUE THREAD

**Issue by domenic** [tastejs/todomvc-backbone-es6#11]
Modules use string IDs, not identifiers (`module "todo-app"`, not `module TodoApp`).

In general, the module usage is a bit muddled. For example, you're using globals for `Backbone`, but an inline module for `TodoApp`. And inline modules are generally not produced by humans, but instead by build tools. (Humans produce files that use top-level `import` and `export`.)

I know it'd be nice to show off modules, but I'm not sure this is the right way to do it.

**Comment by addyosmani** [comment]
All valid points!. My original intention was to show off how to use ES6 + modules + the module loader API using the [polyfill](https://github.com/ModuleLoader/es6-module-loader/) we wrote for it. Sadly, because Traceur has it's own outdated module support and hasn't yet implemented the loader API, I'll need to wait until I can patch Traceur with the loader in order to demonstrate this using best practices.

If I can't wrangle traceur/the source to use string IDs I will add a note about this in the comments.

**Comment by sindresorhus** [comment]
@addyosmani can't we convince them with cake.

**Comment by addyosmani** [comment]
We now use a spec-compatible module loader polyfill that works alongside Traceur and have updated our code to reflect the latest module syntax recommendations.
