### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by addyosmani** [tastejs/todomvc-backbone-es6#6]
The next step I'd like to tackle is separating out `app.js` into ES6 modules.

We could follow the same overall file structure adopted by the official Backbone app https://github.com/tastejs/todomvc/tree/gh-pages/architecture-examples/backbone/js but just make each individual file a module, or opt for something cleaner.

Traceur has support for modules (though it's unclear how close to the latest specs) and I'm considering using https://github.com/ModuleLoader/es6-module-loader which we put together as a module loader polyfill (that is spec compliant).

**Comment by addyosmani** [comment]
@arv I want to try getting the Module Loader polyfill working with Traceur using this as a test case.  Right now I'm considering patching the callback for a module actually have been loaded so that we then pass on dynamic transpilation/execution of it to Traceur. Does that sound reasonable or should we approach this internal to Traceur from the get go?

**Comment by arv** [comment]
I haven't looked at your loader polyfill in detail so I'm not too familiar with the changes since I implemented the module loader for Traceur a few years back.
- Once a file is loaded, it needs to be parsed and all further imports need to be gathered.
- Once all files have been loaded we need to validate the exports
- Once all exports are validated, we can transform and execute the code

Take a look at https://github.com/google/traceur-compiler/blob/master/src/runtime/modules.js#L372

**Comment by addyosmani** [comment]
Thanks to Guy we now support the latest version of the Module spec and ModuleLoader working alongside Traceur.
